import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logo from "@/public/logo.svg";
import { ChevronDown, Menu, Search } from "lucide-react";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bizify Digital Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <header className="bg-[#FBFBFB] flex items-center justify-between p-4">
          <Image src={logo} alt="Bizify Logo" width={150} height={50} />

          <nav>
            <ul className="flex gap-4">
              <li className="flex gap-0.5">
                {" "}
                <a href="#" >Home</a> <ChevronDown />
              </li>
              <li>
                <a href="#">About us</a>
              </li>
              <li className="flex gap-0.5">
                {" "}
                <a href="#">Pages</a>
                <ChevronDown />
              </li>
              <li className="flex gap-0.5">
                <a href="#">Blog</a> <ChevronDown />
              </li>
              <li>
                <a href="#">Contact</a>
              </li>
            </ul>
<Search />            <Menu />
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
